### ISSUE TITLE
logging.info(f'last_percent loaded with a value of {last_percent}')

### ISSUE THREAD

**Issue by tandrysek** [ipv6freely/bmw2018#1]
Hello,
i tried run script on my MacBook-Pro$ python bmw.py 

and it shows: 
File "bmw.py", line 101
  logging.info(f'last_percent loaded with a value of {last_percent}')

What i doing wrong? Thnx.

**Comment by ipv6freely** [comment]
@tandrysek What version of Python?

**Comment by tandrysek** [comment]
MacBook-Pro$ python --version
**Python 2.7.10**

**Comment by ipv6freely** [comment]
@tandrysek There's your problem. F-strings only work in Python 3. You can either use Python 3, or you can modify the code to remove the f-strings and use older methods of formatting your output. There may be other things that break in Python 2, though.
